# How does tensor work?

In [15]:
import torch
from neuron.activation_functions import sigmoid

### Toy example

In [5]:
y = x**3 + 0.1 * x**2 + 1.
y

tensor([2.1000], grad_fn=<AddBackward0>)

In [6]:
y.backward()

In [7]:
x.grad       # 3x^2 + 0.1 * 2x @ x=1. = 3.2

tensor([3.2000])

### Perceptron

In [9]:
x = torch.ones(1, requires_grad=True);

weight = 0.5
bias = 2.
z = weight * x + bias
z

tensor([2.5000], grad_fn=<AddBackward0>)

In [10]:
activation = torch.sigmoid(z)        # sigmoid(0.5x + 2)
activation

tensor([0.9241], grad_fn=<SigmoidBackward>)

In [11]:
activation.backward()

In [12]:
x.grad          # sigmoid(0.5x + 2) * (1 - sigmoid(0.5x + 2)) @ x = 1. = 

tensor([0.0351])

In [17]:
dact_dz = sigmoid(weight * 1. + bias) * (1 - sigmoid(weight * 1. + bias))
dz_dx = 0.5

In [14]:
dact_dz * dz_dx

0.03505185827255403